### ISSUE TITLE
GetVehicleMatrix

### ISSUE THREAD

**Issue by minhthien2563** [Leonardo541/matrix#1]
Hello, maybe i need ur help with my problem. I try used GetVehicleMatrix from YSF but the following error appears "number of arguments does not match definition" and "array must be indexed (variable "mat")"

I copied ur code in example file and paste it in OnPlayerEditDynamicObject. Im used float of callback for code.

```
new mat[MATRIX];
new pos[VECTOR];
new rot[VECTOR];

mat = GetVehicleMatrix(vehicleid);
pos = Matrix_GetOffsetPosition(mat, Vector(x, y, z));
rot = Matrix_GetOffsetRotation(mat, Vector(rx, ry, rz));
```

**Comment by Leonardo541** [comment]
I'm sorry I did not answer earlier

You can use GetVehicleMatrix from YSF like this: 

```
GetVehicleMatrix(vehicleid, mat[MAT_RIGHT][VEC_X], mat[MAT_RIGHT][VEC_Y], mat[MAT_RIGHT][VEC_Z], mat[MAT_FRONT][VEC_X], mat[MAT_FRONT][VEC_Y], mat[MAT_FRONT][VEC_Z], mat[MAT_UP][VEC_X], mat[MAT_UP][VEC_Y], mat[MAT_UP][VEC_Z]);
GetVehiclePos(vehicleid, mat[MAT_POS][VEC_X], mat[MAT_POS][VEC_Y], mat[MAT_POS][VEC_Z]);
```
